services:
  - type: web
    name: freqtrade-bot
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: FREQTRADE__EXCHANGE__KEY
        sync: false
      - key: FREQTRADE__EXCHANGE__SECRET
        sync: false
      - key: FREQTRADE__EXCHANGE__PAIR_WHITELIST
        value: '["ETH/USD"]'
      - key: FREQTRADE__PAIRLIST__USE_VOLUME_FILTER
        value: "false"
    autoDeploy: true
    
